ldap-oauth2/application/urls.py
# from django.conf.urls import url
from django.urls import re_path as url

from .views import ApplicationRegistrationView, ApplicationUpdateView, CustomAuthorizationView

urlpatterns = [
    url(r'^authorize/$', CustomAuthorizationView.as_view(), name='authorize'),
    url(r'^applications/register/$', ApplicationRegistrationView.as_view(), name='register'),
    url(r'^applications/(?P<pk>\d+)/update/$', ApplicationUpdateView.as_view(), name='update'),
]

ldap-oauth2/sso/urls.py
import re

import oauth2_provider.urls
from django.conf import settings

from django.urls import re_path as url
from django.conf.urls import include

# from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.views.static import serve

import account.urls
import application.urls
import resources.urls
import user_resource.urls
import widget.urls
import internal.urls

from .views import DocView, IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('doc/', DocView.as_view(), name='doc'),
    url(r'^doc/(?P<tab>[\w-]+\w+)/$', DocView.as_view(), name='doc'),
    path('admin/', admin.site.urls),
    path('oauth/', include((application.urls, 'oauth'), namespace='oauth')),
    path('oauth/', include((oauth2_provider.urls, 'oauth2_provider'), namespace='oauth2_provider')),
    path('account/', include((account.urls, 'account'), namespace='account')),
    path('user/', include((user_resource.urls, 'user'), namespace='user')),
    path('resources/', include((resources.urls, 'resources'), namespace='resources')),
    path('internal/', include((internal.urls, 'internal'), namespace='internal')),
    path('widget/', include((widget.urls, 'widgets'), namespace='widgets')),
]

# Fail safe! If nginx is down, this might come handy.
#urlpatterns += [
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.STATIC_ROOT,
#        }
#        ),
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.MEDIA_ROOT,
#        }
#        ),
#]

ldap-oauth2/user_resource/urls.py
# from django.conf.urls import include, url
from django.conf.urls import include
from django.urls import re_path as url
from rest_framework.routers import DefaultRouter

from .views.api import UserViewset
from .views.home import (ApplicationRevokeView, UpdateInstiAddressView, UpdateMobileNumberView, UpdateProgramView,
                         UpdateSecondaryEmailView, UpdateUserProfilePicture, UpdateUserSex, UserApplicationListView,
                         UserHomePageView)

router = DefaultRouter()
router.register('user', UserViewset, basename='user')

urlpatterns = [
    url(r'^api/', include((router.urls, 'api'), namespace='api')),
    url(r'^$', UserHomePageView.as_view(), name='home'),
    url(r'^update_pp/$', UpdateUserProfilePicture.as_view(), name='update_pp'),
    url(r'^update_address/$', UpdateInstiAddressView.as_view(), name='update_address'),
    url(r'^update_program/$', UpdateProgramView.as_view(), name='update_program'),
    url(r'^update_mobile/$', UpdateMobileNumberView.as_view(), name='update_mobile'),
    url(r'^update_email/$', UpdateSecondaryEmailView.as_view(), name='update_email'),
    url(r'^update_sex/$', UpdateUserSex.as_view(), name='update_sex'),
    url(r'^settings/$', UserApplicationListView.as_view(), name='settings'),
    url(r'^revoke_app/(?P<pk>\d+)/$', ApplicationRevokeView.as_view(), name='revoke_app'),
]

ldap-oauth2/widget/urls.py
# from django.conf.urls import url
from django.urls import re_path as url
from .views import LoginWidget

urlpatterns = [
    url(r'login/$', LoginWidget.as_view(), name='login'),
]

ldap-oauth2/sso/views.py
from django.core.mail.message import make_msgid
from django.views.generic import TemplateView

from account.models import UserProfile
from core.utils import DEGREES, HOSTELS, SEXES, SORTED_DISCIPLINES, TabNav


class IndexView(TemplateView):
    template_name = 'sso/index.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if request.user.is_authenticated:
            context['base_template'] = 'sso/logged_in.html'
        else:
            context['base_template'] = 'sso/root.html'

        return self.render_to_response(context)


tabs_list = [
    ('basic', 'Basic', 'basic.html'),
    ('api', 'APIs', 'api.html'),
    ('widgets', 'Widgets', 'widget.html'),
    ('best-practices', 'Best Practices', 'practices.html'),
    ('libraries', 'Libraries', 'library.html'),
    ('policy', 'Policy', 'policy.html'),
]


class DocView(TemplateView):
    template_name = 'sso/5-minutes-doc.html'
    tabs = [TabNav(tab[0], tab[1], tab[2], 'doc', tab[0] == 'basic') for tab in tabs_list]

    def get_context_data(self, **kwargs):
        context = super(DocView, self).get_context_data(**kwargs)
        context['login_js_url'] = 'https://gymkhana.iitb.ac.in/profiles/static/widget/js/login.min.js'
        context['Message_ID'] = make_msgid()
        context['SORTED_DISCIPLINES'] = SORTED_DISCIPLINES
        context['DEGREES'] = DEGREES
        context['HOSTELS'] = HOSTELS
        context['SEXES'] = SEXES
        context['USER_TYPES'] = UserProfile.objects.values_list('type').distinct()

        # Mark all tabs as inactive
        for tab_ in self.tabs:
            tab_.is_active = False

        tab = context.get('tab', '')
        for tab_ in self.tabs:
            if tab == tab_.tab_name:
                tab = tab_
                break
        else:
            tab = self.tabs[0]
        tab.is_active = True
        context['tabs'] = self.tabs
        context['active_tab'] = tab
        return context

ldap-oauth2/user_resource/views/api.py
import logging
from smtplib import SMTPException

from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from oauth2_provider.contrib.rest_framework.permissions import TokenHasScope
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.status import HTTP_400_BAD_REQUEST

from ..models import SentMessage
from ..oauth import DEFAULT_FIELDS, SCOPE_TO_FIELD_MAP, USER_FIELDS
from ..serializers import SendMailSerializer, UserSerializer

logger = logging.getLogger(__name__)


class UserViewset(viewsets.GenericViewSet):
    required_scopes = ['basic']
    permission_classes = [TokenHasScope]
    serializer_class = UserSerializer

    def get_queryset(self):
        token = self.request.auth
        user = token.user
        return User.objects.all().filter(pk=user.id)

    def list(self, request):
        user_queryset = self.get_queryset().first()
        fields = request.query_params.get('fields')
        granted_scopes = request.auth.scope
        granted_scopes = granted_scopes.split()
        granted_fields = []
        for scope in granted_scopes:
            granted_fields.extend(SCOPE_TO_FIELD_MAP[scope])

        if fields is None:
            fields = []
        else:
            fields = fields.split(',')
            fields = [field.strip() for field in fields if field.strip()]
        fields = set(fields)
        all_fields = set(DEFAULT_FIELDS + USER_FIELDS)
        undefined_fields = list(fields - all_fields)
        if undefined_fields:
            error_message = {
                'detail': 'fields (%s) not found' % ', '.join(undefined_fields)
            }
            return Response(error_message, status=HTTP_400_BAD_REQUEST)

        allowed_fields = list(set(fields).intersection(set(granted_fields)))
        user_serialized = UserSerializer(user_queryset, context={'fields': allowed_fields}).data
        return Response(user_serialized)

    @action(methods=['POST'], required_scopes=['send_mail'], detail=False)
    def send_mail(self, request):
        token = request.auth
        app = token.application
        app_admin = token.application.user
        user = self.get_queryset().first()
        mail = SendMailSerializer(data=request.data)
        if mail.is_valid():
            subject = '[SSO] [%s] %s' % (app.name, mail.validated_data.get('subject'))
            body = ('%s\n\n\n'
                    'Sent via SSO by %s\n\n'
                    'You received this message because you\'ve provided the email sending'
                    ' permission to the application')
            body = body % (mail.validated_data.get('message'), app.name)
            from_email = '%s <%s>' % (app_admin.first_name, app_admin.email)
            email_message = EmailMessage(
                subject=subject,
                body=body,
                from_email=from_email,
                to=[user.email],
                reply_to=mail.validated_data.get('reply_to'),
            )
            message = email_message.message()
            sent_message = SentMessage(
                message_id=message['Message-ID'],
                sender=app,
                user=user,
            )
            response_data = {
                'Message-ID': message['Message-ID'],
                'status': True,
            }
            try:
                email_message.send()
                sent_message.status = True
                response_data['status'] = True
            except SMTPException as err:
                sent_message.status = False,
                sent_message.error_message = err.message
                logger.error(err)
                response_data['status'] = False
            sent_message.save()
            return Response(response_data)
        else:
            return Response(mail.errors, status=HTTP_400_BAD_REQUEST)

ldap-oauth2/widget/views.py
import re

from django.utils.decorators import method_decorator
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import TemplateView


class LoginWidget(TemplateView):
    template_name = 'widget/login.html'
    hex_color_regex = re.compile(r'^(?:[0-9a-fA-F]{3}){1,2}$')

    def get_context_data(self, **kwargs):
        context = super(LoginWidget, self).get_context_data(**kwargs)
        context['button_div_bg_color'] = '#303F9F'
        context['button_anchor_color'] = '#FFFFFF'
        context['logout_anchor_color'] = '#727272'
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        query_params = []
        for query_param in ['client_id', 'scope', 'redirect_uri', 'state', 'response_type']:
            value = request.GET.get(query_param)
            if value:
                query_params.append('%s=%s' % (query_param, value))
        query = '&'.join(query_params)
        context['query'] = query

        new_window = request.GET.get('new_window')
        if new_window in ['true', 'yes', 'True', '1']:
            new_window = True
        else:
            new_window = False
        context['new_window'] = new_window

        for color_face in ['button_div_bg_color', 'button_anchor_color', 'logout_anchor_color']:
            color_val = request.GET.get(color_face)
            if color_val and self._verify_hex_color(color_val):
                context[color_face] = '#%s' % color_val

        return self.render_to_response(context)

    @method_decorator(xframe_options_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginWidget, self).dispatch(request, *args, **kwargs)

    def _verify_hex_color(self, hex_val):
        return self.hex_color_regex.match(hex_val) is not None

ldap-oauth2/templates/sso/doc_includes/api.html
{% load absolute_url %}

<h4>Before reading this section, go through <code>basic</code> section once</h4>

<h3 id="user_resources_api">Accessing API</h3>
<ul class="doc">
    By now you have created API, got access_token and authenticated user. But still you don't know who the
    user is?
    For that purpose you need to access user resources API. Currently API is limited to few user resources
    only and
    in future we're planning to expand it a lot. <br>
    User data is stored at <a href="{% url 'user:home' %}" target="_blank">sso</a> server. And as an
    application
    developer you should encourage users to update their data there.

    <li>
        Available user resources are:
        <ul>
            <li>
                <b>basic:</b> Basic resource includes <code>id</code> only. You need to have <b>basic</b>
                scope for
                this
            </li>
            <li>
                <b>first_name:</b> First name of the user. You need to have <b>profile</b> scope for this
            </li>
            <li>
                <b>last_name:</b> Last name of the user. You need to have <b>profile</b> scope for this
            </li>
            <li>
                <b>type:</b> Type of user. ex: ug, pg, dd etc. You need <b>profile</b> scope for this
            </li>
            <li>
                <b>username:</b> LDAP username of the user. You need to have <b>ldap</b> scope for this
            </li>
            <li>
                <b>profile_picture:</b> Profile picture of user. This will be a URL. You need to have
                <b>picture</b> scope for this
            </li>
            <li>
                <b>sex:</b> Sex of the user. It can be Male, Female or Other. You need to have <b>sex</b> scope for
                this
            </li>
            <li>
                <b>email:</b> LDAP email (username@iitb.ac.in) of the user. You need to have
                <b>ldap</b> scope for this
            </li>
            <li>
                <b>mobile:</b> Mobile includes mobile number of client fetched from LDAP. You need to have
                <b>phone</b> scope for this
            </li>
            <li>
                <b>roll_number:</b> Roll number includes roll number of client fetched from LDAP. You need
                to have
                <b>program</b> scope for this
            </li>
            <li>
                <b>contacts:</b> Phone resource includes all the contact number provided by client. You need
                to have
                <b>phone</b> scope for this
            </li>
            <li>
                <b>insti_address:</b> This resource includes user's room number and hoste number. You need
                <b>insti_address</b> scope for this
            </li>
            <li>
                <b>program:</b> Program includes user's joining year, (expected) graduation year, department
                and
                degree. You need to have <b>program</b> scope for this
            </li>
            <li>
                <b>secondary_emails:</b> This resource includes user's emails other than default ldap email.
                You
                need to have <b>secondary_emails</b> scope for this
            </li>
        </ul>
    </li>

    <li>
        To access user's resources make a GET request to
        {% url 'user:api:user-list' as user_resource_url %}
        <code>{% absolute_url user_resource_url %}?fields=RESOURCE_LIST</code>. <code>fields</code> is optional
        parameter
        and by default it includes <code>basic</code> fields. <code>RESOURCE_LIST</code> is comma-separated
        list of
        user resources. You should include <code>access_token</code> in request header as
<pre>
GET {{ user_resource_url }} HTTP/1.1
Host: {{ request.get_host }}
Authorization: Bearer ACCESS_TOKEN
</pre>
    </li>
    <li>
        The output for <code>{% absolute_url user_resource_url %}?fields=first_name,last_name,type,profile_picture,sex,username,email,program,contacts,insti_address,secondary_emails,mobile,roll_number</code>
        will look like (assuming you've enough scopes)
<pre>
{
  "id": 1,
  "username": "username",
  "first_name": "First Name",
  "type": "TYPE",
  "profile_picture": "{% url 'index' %}/path/to/profile_picture_file"
  "last_name": "Last Name",
  "sex": "SEX",
  "email": "username@iitb.ac.in",
  "mobile": "0123456789",
  "roll_number": "123456789",
  "program": {
    "id": 1,
    "department": "DEPARTMENT",
    "department_name": "FULL_DEPARTMENT_NAME",
    "join_year": 2012,
    "graduation_year": 2016,
    "degree": "DEGREE",
    "degree_name": "FULL_DEGREE_NAME"
  },
  "secondary_emails": [
    {
      "id": 1,
      "email": "user_email@gmail.com"
    }
  ],
  "contacts": [
    {
      "id": 1,
      "number": "9876543210"
    }
  ],
  "insti_address": {
    "id": 1,
    "room": "room_number",
    "hostel": "HOSTEL",
    "hostel_name": "FULL_HOSTEL_NAME",
  }
}
</pre>
        Here you'll get only resources permitted by user in scope.
    </li>
    <li>
        <code>DEPARTMENT</code> list:
        <ul>
            <li><b><code>DEPARTMENT_NAME:</code></b> <em><code>FULL_DEPARMENT_NAME</code></em></li>
            {% for code, full_name in SORTED_DISCIPLINES %}
                <li><b>{{ code }}:</b> <em>{{ full_name }}</em></li>
            {% endfor %}
        </ul>
    </li>
    <li>
        <code>DEGREE</code> list:
        <ul>
            <li><b><code>DEGREE:</code></b> <em><code>FULL_DEGREE_NAME</code></em></li>
            {% for code, full_name in DEGREES %}
                <li><b>{{ code }}:</b> <em>{{ full_name }}</em></li>
            {% endfor %}
        </ul>
    </li>
    <li>
        <code>HOSTEL</code> list:
        <ul>
            <li><b><code>HOSTEL:</code></b> <em><code>FULL_HOSTEL_NAME</code></em></li>
            {% for code, full_name in HOSTELS %}
                <li><b>{{ code }}:</b> <em>{{ full_name }}</em></li>
            {% endfor %}
        </ul>
    </li>
    <li>
        <code>SEX</code> list:
        <ul>
            {% for code, full_name in SEXES %}
                <li><b>{{ code }}:</b> <em>{{ full_name }}</em></li>
            {% endfor %}
        </ul>
    </li>
    <li>
        <code>TYPE</code> list:
        <ul>
            {% for code in USER_TYPES %}
                <li><b>{{ code|first }}</b></li>
            {% endfor %}
        </ul>
    </li>

</ul>

<h3 id="send_mail_api">Send Mail API</h3>
<ul class="doc">
    This application also provides a "send mail" API, which allows your application to send email to user
    from
    a simple endpoint. You need to have <code>send_mail</code> permission from user for this to work
    <li>
        Create a POST request like this:
<pre>
POST {% url 'user:api:user-send-mail' %} HTTP/1.1
Host: {{ request.get_host }}
Authorization: Bearer ACCESS_TOKEN
Content-Type: application/json


{
    "subject": "Hello World",
    "message": "Lorem Ipsum",
    "reply_to": [
        "email_address_1@example.com",
        "email_address_2@exapple.com"
    ]
}
</pre>

    <li>
        Response Data:
<pre>
{
    "Message-ID": "{{ Message_ID }}",
    "status": true
}
</pre>
        <code>Message-ID</code> is a unique identifier for each sent message. Its format is <code>
        &lt;timestamp.pid.random_number@fqdn&gt;</code>. <code>Message-ID</code> in this example is
        actually a valid generated identifier which is changing each time you open this page!<br>
        <code>status</code> is either <b>true</b> or <b>false</b> depending on whether message was
        sent successfully. Remember <code>status: true</code> doesn't guarantee delivery of message
    </li>
    <li>
        Final subject will be "[SSO] [&lt;APPLICATION_NAME&gt;] &lt;YOUR SUBJECT&gt;". This is
        automatically
        generated.
    </li>
    <li>
        Final message will have these line appended:
<pre>
Sent via SSO by &lt;APPLICATION_NAME&gt;

You received this message because you've provided the email sending permission to the application
</pre>
    </li>
    <li>
        <code>reply_to</code> is list of email address where you want your user to reply. Most of
        the mail
        servers honor this protocol and by clicking on "reply" will directly reply to these emails.
    </li>

    <li>
        <strong>DISCLAIMER:</strong>
        <em>We do not store emails in our database. We do store <code>Message-ID</code>, failure state,
            application
            and user for each email. This is stored for debugging and performance improvement purposes</em>
    </li>
</ul>

ldap-oauth2/templates/sso/doc_includes/basic.html
{% load static %}
{% load absolute_url %}

<h3 id="registration">Registering application</h3>
<ul class="doc">
    <li>To register an application open <a href="{% url 'oauth:register' %}" target="_blank">this link</a>
    </li>
    <li>Provide a nice name to your application, write a brief description and add a cool little logo</li>
    <li>Unless your application is entirely client based (like JS), use <code>Client Type:
        confidential</code>
        and <code>Authorization grant type: authorization code</code></li>
    <li>Add a list of redirect URIs. Redirect URIs are the URLs where your client will be redirected to
        after
        authorization. Let's say you have entered <code>http://www.example.com/authorization/</code>
    </li>
    <li>Click Submit! That's it, you've registered an application. You can access your applications at
        <a href="{% url 'oauth2_provider:list' %}" target="_blank">list of applications</a></li>
</ul>

<h3 id="authorization_workflow">Authorization workflow</h3>
<ul class="doc">
    <li>
        To authenticate a client, add some button to your webpage for login like
        <a class="btn btn-primary">Login With SSO</a>
    </li>
    <li>
        By clicking to that button, your client should be redirect to

        {% url 'oauth:authorize' as authorization_url %}
        <pre> {% absolute_url authorization_url %}?client_id=YOUR_CLIENT_ID&response_type=code&scope=basic&redirect_uri=REDIRECT_URI&state=some_state</pre>
        <code>scope</code>, <code>redirect_uri</code> and <code>state</code> are optional here.
        <code>state</code>
        can be anything, it will be returned back to you after authorization. You can use this to rememeber
        your
        client. <code>redirect_uri</code> should be from redirect uri you registered for app. If nothing is
        provided
        here then first redirect uri will be assumed to be default. From now onwards we'll call it
        <code>REDIRECT_URI</code>. <code>scope</code> is a string of space separated scopes.
        <ul>
            Available scopes are
            <li><strong>basic</strong>: <em>It includes your user id from SSO server (not the ldap id)</em>
            </li>
            <li><strong>profile</strong>: <em>Your first_name and last_name and type</em></li>
            <li><strong>picture</strong>: <em>Your profile picture</em></li>
            <li><strong>sex</strong>: <em>You sex - Male, Female or Other</em></li>
            <li><strong>ldap</strong>: <em>Your ldap username and email</em></li>
            <li><strong>phone</strong>: <em>Your contact number including additional numbers</em></li>
            <li><strong>insti_address</strong>: <em>Your address inside institute</em></li>
            <li><strong>program</strong>: <em>Your roll number, department, course, joining year and
                graduation
                year</em></li>
            <li><strong>secondary_emails</strong>: <em>Your alternate emails</em></li>
            <li><strong>send_mail</strong>: <em>Allow application to send you email via SSO</em></li>
        </ul>
        If nothing is provided in <code>scope</code> parameter then <strong>basic</strong> scope will be
        assumed.
        <br>
        Now your client will see something similar to
        <a href="{% static 'sso/img/authorization_image.png' %}" target="_blank">this image</a>
    </li>
    <li>If client has denied your request you'll get <code>REDIRECT_URI?error=access_denied</code> else
        you'll get
        <code>REDIRECT_URL?state=some_state&code=AUTHORIZATION_CODE</code>. <code>AUTHORIZATION_CODE</code>
        will be
        an alpha-numeric code
    </li>
    <li>
        <b>Or ignore all above points and use our widget</b>. Check widget section on top
    </li>
</ul>

<h3 id="token_exchange">Token Exchange</h3>
<ul class="doc">
    Now assuming that you've received <code>AUTHORIZATION_CODE</code> after client has authorized itself.
    <code>AUTHORIZATION_CODE</code> is short lived code. You need to redeem it quickly to get
    <code>access_token</code>
    <li>
        {% url 'oauth2_provider:token' as token_url %}
        Make a request for token exchange to <code>{% absolute_url token_url %}</code>. You're HTTP request
        will
        look like
<pre>
POST {{ token_url }} HTTP/1.1
Host: {{ request.get_host }}
Authorization: Basic AUTHENTICATION_TOKEN
Content-Type: application/x-www-form-urlencoded; charset=UTF-8


code=AUTHORIZATION_CODE&redirect_uri=REDIRECT_URI&grant_type=authorization_code
</pre>
        <b><code>AUTHENTICATION_TOKEN</code> is base64 of <code>CLIENT_ID:CLIENT_SECRET</code>.</b>
        <b>Here <code>code</code>, <code>redirect_uri</code> and <code>grant_type</code> are compulsory</b>
    </li>
    <li>
        Now assuming you've created a valid http request here, you'll now get <code>access_token</code> and
        <code>refresh_token</code> as json
<pre>
{
    "access_token" : "access_token",
    "token_type" : "Bearer",
    "expires_in" : "36000",
    "refresh_token" : "refresh_token",
    "scope" : "basic"
}
</pre>
        <code>access_token</code> and <code>refresh_token</code> are both alpha-numeric strings<br>
        <code>access_token</code> are short living tokens and will expire in 10 hours.
        <code>refresh_token</code>
        are
        long living tokens and you should save them in your database for future purpose.<br>
        <code>scope</code> is space separated list of scopes that client has granted to you. You should also
        save
        these scope in your database for reference purpose. <br>
        At this point you should also create session for your client on your website since client is
        authenticated
        now
    </li>
</ul>

<h3 id="refresh_token">Refreshing Token</h3>
<ul class="doc">
    Since <code>access_token</code> will expire quickly, you need to generate new <code>access_token</code>
    with
    <code>refresh_token</code>
    <li>
        Refreshing token is similar to token exchange with (almost) same http request to server. Only your
        post data
        will changed and new post data will be
        <code>refresh_token=REFRESH_TOKEN&grant_type=refresh_token</code>
    </li>
    <li>
        The response JSON will be almost same with only <code>access_token</code> and
        <code>refresh_token</code>
        both changed. You need to update your <code>refresh_token</code> in database
    </li>
</ul>

<h3 id="revoke_token">Revoking Token</h3>
<ul class="doc">
    <li>
        To revoke client access, create the following http request
<pre>
POST {% url 'oauth2_provider:revoke-token' %} HTTP/1.1
Host: {{ request.get_host }}
Content-Type: application/x-www-form-urlencoded; charset=UTF-8


token=TOKEN&client_id=CLIENT_ID&client_secret=CLIENT_SECRET&token_type_hint=TOKEN_TYPE
</pre>
        Here <code>TOKEN</code> can be <code>access_token</code> or <code>refresh_token</code><br>
        <code>token_type_hint</code> is optional. <code>TOKEN_TYPE</code> should be either
        <em>access_token</em> or
        <em>refresh_token</em>

    </li>
</ul>

ldap-oauth2/templates/sso/doc_includes/library.html
<h4>We are trying to provide best we can. Efforts from your side are appreciated. Here are few library
    implementations</h4>

<h3>PHP</h3>

<p class="doc">
    <a href="https://github.com/BijoySingh" target="_blank">BijoySingh</a> is maintaining a
    <a href="https://github.com/BijoySingh/IITB-OAuth-PHP" target="_blank">PHP library</a>
    The documentation is present <a href="http://bijoysingh.github.io/IITB-OAuth-PHP/" target="_blank">here</a>
</p>

<h3>Django</h3>

<p class="doc">
    <a href="https://github.com/nautatva/iitb_oauth/" target="_blank">This repo</a> has the source code for django
    library. The pypi release is present <a href="https://pypi.org/project/iitb-oauth/" target="_blank">here</a>
</p>

<h3>Python</h3>

<p class="doc">
    Python library is maintained <a href="https://github.com/DheerendraRathor/iitb_oauth_py" target="_blank">here</a>.
    This is currently in alpha version
</p>

ldap-oauth2/templates/sso/doc_includes/policy.html
<h3>Gymkhana Profiles Policy</h3>

<p class="doc">
    <ol class="doc">
        <li>
            Gymkhana Profiles is intended to be used ONLY by applications built by students
            and hosted in the server infrastructure of IIT Bombay Gymkhana
        </li>
        <li>
            Any application registered must be verified before deployment. Unverified applications
            will have a cap on the number of users for security reasons, along with a
            warning to alert the user about the same.
        </li>
        <li>
            Only applications running on Gymkhana servers and built by students will be verified.
            Express permission of Head, Computer Center will be required to make any exceptions to
            this rule. For all applications not running on Gymkhana servers, usage of IITB SSO is
            strongly advised instead. MLC CANNOT make exceptions to this rule unilaterally.
        </li>
        <li>
            To get your application verified, write an email to mlc@iitb.ac.in. Computer Center or MLC
            may require specific compliances and/or documents before your application is verified.
        </li>
        <li>
            Only applications created with an institutional LDAP ID will be verified. Existing
            applications can be transferred upon request to another account. If no relevant institutional
            LDAP ID exists, the application must be transferred to MLC.
        </li>
        <li>
            In case of any dispute, the decision of Head, Computer Center and Dean of Student Affairs
            shall be final and binding.
        </li>
        <li>
            This policy may be altered by Computer Center without prior notification.
        </li>
    </ol>
</p>

ldap-oauth2/templates/sso/doc_includes/practices.html
<h3>While developing an application based on SSO, keep following things in mind!</h3>
<ul class="doc">
    <li>
        Don't ask for too much permissions. Ask for necessary permissions only. Respect user's privacy!
    </li>
    <li>
        Store <code>refresh_token</code> and <code>access_token</code> on your server. They can be used for
        background requests.
    </li>
    <li>
        Maintain sessions for your user! Don't overwhelm the SSO server by authorization requests.
    </li>
    <li>
        If user hasn't provided the necessary permissions, <b>revoke the token!</b> Otherwise user will see
        your application in list of connected apps.
    </li>
    <li>
        Use login-button widget!
    </li>
</ul>