ldap-oauth2/application/urls.py
# from django.conf.urls import url
from django.urls import re_path as url

from .views import ApplicationRegistrationView, ApplicationUpdateView, CustomAuthorizationView

urlpatterns = [
    url(r'^authorize/$', CustomAuthorizationView.as_view(), name='authorize'),
    url(r'^applications/register/$', ApplicationRegistrationView.as_view(), name='register'),
    url(r'^applications/(?P<pk>\d+)/update/$', ApplicationUpdateView.as_view(), name='update'),
]

ldap-oauth2/sso/urls.py
import re

import oauth2_provider.urls
from django.conf import settings

from django.urls import re_path as url
from django.conf.urls import include

# from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.views.static import serve

import account.urls
import application.urls
import resources.urls
import user_resource.urls
import widget.urls
import internal.urls

from .views import DocView, IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('doc/', DocView.as_view(), name='doc'),
    url(r'^doc/(?P<tab>[\w-]+\w+)/$', DocView.as_view(), name='doc'),
    path('admin/', admin.site.urls),
    path('oauth/', include((application.urls, 'oauth'), namespace='oauth')),
    path('oauth/', include((oauth2_provider.urls, 'oauth2_provider'), namespace='oauth2_provider')),
    path('account/', include((account.urls, 'account'), namespace='account')),
    path('user/', include((user_resource.urls, 'user'), namespace='user')),
    path('resources/', include((resources.urls, 'resources'), namespace='resources')),
    path('internal/', include((internal.urls, 'internal'), namespace='internal')),
    path('widget/', include((widget.urls, 'widgets'), namespace='widgets')),
]

# Fail safe! If nginx is down, this might come handy.
#urlpatterns += [
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.STATIC_ROOT,
#        }
#        ),
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.MEDIA_ROOT,
#        }
#        ),
#]

ldap-oauth2/user_resource/urls.py
# from django.conf.urls import include, url
from django.conf.urls import include
from django.urls import re_path as url
from rest_framework.routers import DefaultRouter

from .views.api import UserViewset
from .views.home import (ApplicationRevokeView, UpdateInstiAddressView, UpdateMobileNumberView, UpdateProgramView,
                         UpdateSecondaryEmailView, UpdateUserProfilePicture, UpdateUserSex, UserApplicationListView,
                         UserHomePageView)

router = DefaultRouter()
router.register('user', UserViewset, basename='user')

urlpatterns = [
    url(r'^api/', include((router.urls, 'api'), namespace='api')),
    url(r'^$', UserHomePageView.as_view(), name='home'),
    url(r'^update_pp/$', UpdateUserProfilePicture.as_view(), name='update_pp'),
    url(r'^update_address/$', UpdateInstiAddressView.as_view(), name='update_address'),
    url(r'^update_program/$', UpdateProgramView.as_view(), name='update_program'),
    url(r'^update_mobile/$', UpdateMobileNumberView.as_view(), name='update_mobile'),
    url(r'^update_email/$', UpdateSecondaryEmailView.as_view(), name='update_email'),
    url(r'^update_sex/$', UpdateUserSex.as_view(), name='update_sex'),
    url(r'^settings/$', UserApplicationListView.as_view(), name='settings'),
    url(r'^revoke_app/(?P<pk>\d+)/$', ApplicationRevokeView.as_view(), name='revoke_app'),
]

ldap-oauth2/application/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.db import models
from six import python_2_unicode_compatible
# from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _
from oauth2_provider.models import AbstractApplication, AccessToken
from simple_history.models import HistoricalRecords

try:
    from urllib.parse import urljoin
except ImportError:
    from urlparse import urljoin


def application_logo(instance, filename):  # pylint: disable=unused-argument
    filename = filename.split('.')
    if len(filename) > 1:
        ext = filename[-1]
    else:
        ext = "png"
    return os.path.join("app_logo", uuid4().hex + "." + ext)


@python_2_unicode_compatible
class Application(AbstractApplication):
    """
    Extended oauth2_provider.models.AbstractApplication to include application description and logo
    """
    description = models.TextField()
    logo = models.ImageField(upload_to=application_logo, blank=True, null=True)
    is_anonymous = models.BooleanField(default=False,
                                       help_text='Valid for complete anonymous apps. Requires admin permission')
    required_scopes = models.CharField(max_length=256,
                                       help_text='Default non-tracking permissions. '
                                                 'Valid only if application is anonymous', null=True, blank=True)
    private_scopes = models.CharField(max_length=256, help_text='Private API scopes', null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    privacy_policy = models.URLField(null=True, blank=True, help_text='Link of privacy policy of application')
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    is_verified = models.BooleanField(default=False, help_text='Application satisfies all policy constraints. '
                                                               'Read the Gymkhana Profiles/SSO policy before verification')
    is_beta = models.BooleanField(default=False, help_text='Allow unlimited users without verification. '
                                                           'A development warning will be displayed to the user')

    _history_ = HistoricalRecords()

    def get_logo_url(self):
        try:
            url = self.logo.url
            url = urljoin(settings.MEDIA_URL, url)
        except ValueError:
            url = None
        return url

    def get_absolute_url(self):
        return reverse('oauth2_provider:detail', args=[str(self.id)])

    def clean(self):
        super(Application, self).clean()
        if self.authorization_grant_type == AbstractApplication.GRANT_PASSWORD:
            error = _("Resource owner password based grants are not allowed for now")
            raise ValidationError(error)

    def get_user_count(self):
        return AccessToken.objects.all().filter(application=self).values_list('user', flat=True).distinct().count()

    def __str__(self):
        if self.name:
            return self.name
        else:
            return self.client_id

ldap-oauth2/application/forms.py
from django import forms

from core.utils import get_choices_with_blank_dash

from .models import Application


class RegistrationForm(forms.ModelForm):
    name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    authorization_grant_type = forms.ChoiceField(choices=get_choices_with_blank_dash(Application.GRANT_TYPES[:2]),
                                                 widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Application
        fields = (
            'name', 'description', 'logo', 'website', 'privacy_policy', 'client_id', 'client_secret', 'client_type',
            'authorization_grant_type', 'redirect_uris')
        widgets = {
            'description': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 3, }
            ),
            'logo': forms.ClearableFileInput(
                attrs={'class': 'form-control', 'accept': 'image/*', }
            ),
            'website': forms.URLInput(
                attrs={'class': 'form-control', }
            ),
            'privacy_policy': forms.URLInput(
                attrs={'class': 'form-control', }
            ),
            'client_id': forms.TextInput(
                attrs={'class': 'form-control', }
            ),
            'client_secret': forms.TextInput(
                attrs={'class': 'form-control', }
            ),
            'client_type': forms.Select(
                attrs={'class': 'form-control', }
            ),
            'redirect_uris': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4, }
            )
        }

ldap-oauth2/application/views.py
from braces.views import LoginRequiredMixin
from django.views.generic import UpdateView
from oauth2_provider.exceptions import OAuthToolkitError
#from oauth2_provider.http import HttpResponseUriRedirect
from oauth2_provider.models import get_application_model as get_oauth2_application_model
from oauth2_provider.settings import oauth2_settings
from oauth2_provider.views import AuthorizationView
from oauth2_provider.views.application import ApplicationRegistration

from core.utils import get_default_scopes

from .forms import RegistrationForm


class ApplicationRegistrationView(ApplicationRegistration):
    form_class = RegistrationForm


class ApplicationUpdateView(LoginRequiredMixin, UpdateView):
    """
    View used to update an application owned by the request.user
    """
    form_class = RegistrationForm
    context_object_name = 'application'
    template_name = "oauth2_provider/application_form.html"

    def get_queryset(self):
        return get_oauth2_application_model().objects.filter(user=self.request.user)

    def form_valid(self, form, *args, **kwargs):
        application = get_oauth2_application_model().objects.get(id=self.kwargs['pk'])

        if application is not None and application.is_verified:
            if form.cleaned_data.get('client_id', '') != application.client_id:
                form.add_error('client_id', 'Client ID of a verified application cannot be changed')

            if form.cleaned_data.get('name', '') != application.name:
                form.add_error('name', 'Name of a verified application cannot be changed')

            if form.cleaned_data.get('redirect_uris', '') != application.redirect_uris:
                form.add_error('redirect_uris', 'Contact mlc@iitb.ac.in to change redirect URIs of a verified application')

        if len(form.errors) > 0:
            return super(ApplicationUpdateView, self).form_invalid(form)
        return super(ApplicationUpdateView, self).form_valid(form)


class CustomAuthorizationView(AuthorizationView):

    def form_valid(self, form):
        client_id = form.cleaned_data.get('client_id', '')
        application = get_oauth2_application_model().objects.get(client_id=client_id)
        scopes = form.cleaned_data.get('scope', '')
        scopes = set(scopes.split(' '))
        scopes.update(set(get_default_scopes(application)))
        private_scopes = application.private_scopes
        if private_scopes:
            private_scopes = set(private_scopes.split(' '))
            scopes.update(private_scopes)
        scopes = ' '.join(list(scopes))
        form.cleaned_data['scope'] = scopes
        return super(CustomAuthorizationView, self).form_valid(form)

ldap-oauth2/templates/oauth2_provider/application_confirm_delete.html
{% extends "sso/logged_in.html" %}
{% load i18n %}

{% block title %}
    {{ application.name }} - Delete Application
{% endblock %}

{% block body %}
    <div class="center-block">
        <h3 class="text-center">{% trans "Are you sure to delete the application" %} {{ application.name }}?</h3>
        <form method="post" action="{% url 'oauth2_provider:delete' application.pk %}">
            {% csrf_token %}

            <div class="form-group">
                <div class="controls">
                    <a class="btn btn-large btn-success" href="{% url "oauth2_provider:list" %}">{% trans "Cancel" %}</a>
                    <input type="submit" class="btn btn-large btn-danger" name="allow" value="{% trans "Delete" %}"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

ldap-oauth2/templates/oauth2_provider/application_detail.html
{% extends "sso/logged_in.html" %}
{% load i18n %}
{% load static %}

{% block title %}
    {{ application.name }} - Application
{% endblock %}

{% block body %}
    <div class="center-block">
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    {% static 'sso/img/default_logo.jpg' as default_image %}
                    <img class="media-object"
                         src="{{ application.get_logo_url|default_if_none:default_image}}" width="100" height="100" alt="Application Logo">
                </a>
            </div>
            <div class="media-body">
                <h3 class="media-heading">{{ application.name }} ({% if application.is_verified %}Verified{% else %}Unverified{% endif %})</h3>
                {{ application.description }}
            </div>
        </div>

        <form class="form-horizontal" style="margin-top: 20px;">
            <div class="form-group">
                <label for="id_client_id">{% trans 'Client id' %}</label>
                <input id="id_client_id" class="form-control" value="{{ application.client_id }}" disabled/>
            </div>

            <div class="form-group">
                <label for="id_client_secret">{% trans 'Client Secret' %}</label>
                <textarea id="id_client_secret" rows="4" class="form-control" disabled>{{ application.client_secret }}</textarea>
            </div>

            <div class="form-group">
                <label for="id_client_type">{% trans 'Client Type' %}</label>
                <input id="id_client_type" class="form-control" value="{{ application.client_type }}" disabled/>
            </div>

            <div class="form-group">
                <label for="id_client_grant">{% trans 'Authorization Grant Type' %}</label>
                <input id="id_client_grant" class="form-control" value="{{ application.authorization_grant_type }}" disabled/>
            </div>

            <div class="form-group">
                <label for="id_client_uri">{% trans 'Redirect URI' %}</label>
                <textarea id="id_client_uri" rows="4" class="form-control" disabled>{{ application.redirect_uris }}</textarea>
            </div>
        </form>

        <div class="btn-toolbar">
            <a class="btn btn-default" href="{% url "oauth2_provider:list" %}">{% trans "Go Back" %}</a>
            <a class="btn btn-primary" href="{% url "oauth:update" application.id %}">{% trans "Edit" %}</a>

            {% if not application.is_verified %}
            <a class="btn btn-danger" href="{% url "oauth2_provider:delete" application.id %}">{% trans "Delete" %}</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

ldap-oauth2/templates/oauth2_provider/application_form.html
{% extends "sso/logged_in.html" %}
{% load i18n %}

{% block body %}
    <div class="center-block">
        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% block app-form-action-url %}{% url 'oauth:update' application.id %}{% endblock app-form-action-url %}">
            <h3 class="text-center">
                {% block app-form-title %}
                    {% trans "Edit application" %} {{ application.name }}
                {% endblock app-form-title %}
            </h3>
            {% csrf_token %}

            <div class="form-group {% if form.non_field_errors %}error{% endif %}">
                {% for error in form.non_field_errors %}
                    <span class="help-block" style="color:red;">{{ error }}</span>
                {% endfor %}
            </div>

            {% for field in form %}
                <div class="form-group {% if field.errors %}error{% endif %}">
                    <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% if field.field.required %}
                    <span style="color: red;">*</span>
                {% endif %}
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="help-block" style="color:red;">{{ error }}</span>
                        {% endfor %}
                </div>
            {% endfor %}

            <div class="form-group">
                <div class="controls">
                    <a class="btn btn-default" href="{% block app-form-back-url %}{% url "oauth2_provider:detail" application.id %}{% endblock app-form-back-url %}">
                        {% trans "Go Back" %}
                    </a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

ldap-oauth2/templates/oauth2_provider/application_list.html
{% extends "sso/logged_in.html" %}
{% load i18n %}

{% block title %}
    Applications
{% endblock %}

{% block body %}
    <div class="center-block">
        <h3 class="text-center">{% trans "Your applications" %}</h3>
        {% if applications %}
            <ul class="list-group">
                {% for application in applications %}
                    <li class="list-group-item">
                        <a href="{{ application.get_absolute_url }}">{{ application.name }}{% if application.is_verified %} (Verified){% endif %}</a>
                        <span class="badge" title="users" data-toggle="tooltip" data-placement="right">{{ application.get_user_count }}</span>
                    </li>
                {% endfor %}
            </ul>

            <a class="btn btn-success" href="{% url "oauth:register" %}">New Application</a>
        {% else %}
            <p>{% trans "No applications defined" %}. <a
                    href="{% url 'oauth:register' %}">{% trans "Click here" %}</a> {% trans "if you want to register a new one" %}
            </p>
        {% endif %}
    </div>
{% endblock %}

{% block jsLinks %}
    <script type="application/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

ldap-oauth2/templates/oauth2_provider/application_registration_form.html
{% extends "oauth2_provider/application_form.html" %}

{% load i18n %}

{% block title %}
    {% trans "Register Application" %}
{% endblock %}

{% block app-form-title %} {% trans "Register a new application" %}{% endblock app-form-title %}

{% block app-form-action-url %}{% url 'oauth:register' %}{% endblock app-form-action-url %}

{% block app-form-back-url %}{% url "oauth2_provider:list" %}"{% endblock app-form-back-url %}

ldap-oauth2/templates/oauth2_provider/authorize.html
{% extends "sso/logged_in.html" %}
{% load i18n %}
{% load static %}
{% load scope %}

{% block title %}
    Authorization
{% endblock %}

{% block body %}
    {% with max_users_unverified=10 %}
    {% if application and not application.is_verified %}
    <div class="center-block" style="color: red">
        <h2>
            Unverified Application
        </h2>
        <div>
            The application you are trying to authorize has not been verified.
            <br/><br/>
            <b>
                This may be an attempt to trick you. Do not continue unless you are sure
                about the identity of this application.
            </b>

            <br/> <br/>
            If you are the developer of this application, contact mlc@iitb.ac.in for verification.
            Note that only applications running on Gymkhana servers are eligible and
            unverified applications can have a maximum of {{ max_users_unverified }} users.
        </div>
    </div>
    {% endif %}

    {% if application.is_beta %}
    <div class="center-block" style="color: red">
        <h2>
            Public Beta
        </h2>
        <div>
            The application you are trying to authorize is still under development.
            Features may be broken and things may not work as expected.
            Proceed with caution.
        </div>
    </div>
    {% endif %}

    {% if application and not application.is_verified and not application.is_beta and application.get_user_count >= max_users_unverified %}
    <div class="center-block" style="color: red">
        <h4>
            This unverified application ({{ application.name }}) has reached the maximum number of allowed users.
            The application must be verified for further use.
        </h4>
    </div>
    {% else %}
    <div class="center-block">
        {% if not error %}
            <form id="authorizationForm" method="post">
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            {% static 'sso/img/default_logo.jpg' as default_image %}
                            <img class="media-object"
                                 src="{{ application.get_logo_url|default_if_none:default_image }}" width="100"
                                 height="100"
                                 alt="Application Logo">
                        </a>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">{{ application.name }}</h3>
                        {{ application.description }}
                    </div>
                </div>
                <i>Developed by - <a href='mailto:{{ application.user.email }}'>{{ application.user.username }}</a></i>
                {% if application.website %}
                    <div><a href="{{ application.website }}" target="_blank">Visit website</a></div>
                {% endif %}
                {% if application.privacy_policy %}
                    <div><a href="{{ application.privacy_policy }}" target="_blank">Read privacy policies</a></div>
                {% endif %}
                {% csrf_token %}

                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <h3>{% trans "Application requires following permissions" %}</h3>

                <ul class="list-unstyled">
                    {% with zipped_scopes_description=scopes|zip:scopes_descriptions %}
                        {% for scope, description in zipped_scopes_description|get_basic_scope:application %}
                            <li>
                                <div class="checkbox">
                                    <label>
                                        <input checked disabled type="checkbox" id="{{ scope }}_scope"
                                               name="scopes_array"
                                               value="{{ scope }}"/>
                                        {{ description }}
                                    </label>
                                </div>
                            </li>
                        {% endfor %}
                    {% endwith %}
                    {% with zipped_scopes_description=scopes|zip:scopes_descriptions %}
                        {% for scope, description in zipped_scopes_description|remove_basic_scope:application %}
                            <li>
                                <div class="checkbox">
                                    <label>
                                        <input checked type="checkbox" id="{{ scope }}_scope" name="scopes_array"
                                               value="{{ scope }}"/>
                                        {{ description }}
                                    </label>
                                </div>
                            </li>
                        {% endfor %}
                    {% endwith %}
                </ul>

                {{ form.errors }}
                {{ form.non_field_errors }}

                <div class="form-group" style="margin-top: 20px;">
                    <b style="color: #F83838;">Before authorizing, fill your profile <a href="{% url 'user:home' %}" target="_blank">here</a> </b>
                    <div class="controls" style="margin-top: 5px;">
                        <input type="submit" class="btn btn-large btn-danger" value="Cancel"/>
                        <input type="submit" class="btn btn-large btn-success" name="allow" value="Authorize"/>
                    </div>
                </div>
                {% if not application.is_anonymous %}
                    <h5>
                        <b>You can revoke access by visiting
                            <a target='_blank' href="{% url 'user:settings' %}">account settings</a></b>
                    </h5>
                {% endif %}
            </form>

        {% else %}
            <h2>Error: {{ error.error }}</h2>
            <p>{{ error.description }}</p>
        {% endif %}
    </div>
    {% endif %}
    {% endwith %}

{% endblock %}

{% block jsLinks %}
    <script src="{% static 'oauth2_provider/js/authorize.js' %}" type="application/javascript"></script>
{% endblock %}