ldap-oauth2/account/urls.py
# from django.conf.urls import url
# from django.conf.urls import url
from django.urls import re_path as url
 

from .views import LoginView, LogoutView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

ldap-oauth2/sso/urls.py
import re

import oauth2_provider.urls
from django.conf import settings

from django.urls import re_path as url
from django.conf.urls import include

# from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.views.static import serve

import account.urls
import application.urls
import resources.urls
import user_resource.urls
import widget.urls
import internal.urls

from .views import DocView, IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('doc/', DocView.as_view(), name='doc'),
    url(r'^doc/(?P<tab>[\w-]+\w+)/$', DocView.as_view(), name='doc'),
    path('admin/', admin.site.urls),
    path('oauth/', include((application.urls, 'oauth'), namespace='oauth')),
    path('oauth/', include((oauth2_provider.urls, 'oauth2_provider'), namespace='oauth2_provider')),
    path('account/', include((account.urls, 'account'), namespace='account')),
    path('user/', include((user_resource.urls, 'user'), namespace='user')),
    path('resources/', include((resources.urls, 'resources'), namespace='resources')),
    path('internal/', include((internal.urls, 'internal'), namespace='internal')),
    path('widget/', include((widget.urls, 'widgets'), namespace='widgets')),
]

# Fail safe! If nginx is down, this might come handy.
#urlpatterns += [
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.STATIC_ROOT,
#        }
#        ),
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.MEDIA_ROOT,
#        }
#        ),
#]

ldap-oauth2/user_resource/urls.py
# from django.conf.urls import include, url
from django.conf.urls import include
from django.urls import re_path as url
from rest_framework.routers import DefaultRouter

from .views.api import UserViewset
from .views.home import (ApplicationRevokeView, UpdateInstiAddressView, UpdateMobileNumberView, UpdateProgramView,
                         UpdateSecondaryEmailView, UpdateUserProfilePicture, UpdateUserSex, UserApplicationListView,
                         UserHomePageView)

router = DefaultRouter()
router.register('user', UserViewset, basename='user')

urlpatterns = [
    url(r'^api/', include((router.urls, 'api'), namespace='api')),
    url(r'^$', UserHomePageView.as_view(), name='home'),
    url(r'^update_pp/$', UpdateUserProfilePicture.as_view(), name='update_pp'),
    url(r'^update_address/$', UpdateInstiAddressView.as_view(), name='update_address'),
    url(r'^update_program/$', UpdateProgramView.as_view(), name='update_program'),
    url(r'^update_mobile/$', UpdateMobileNumberView.as_view(), name='update_mobile'),
    url(r'^update_email/$', UpdateSecondaryEmailView.as_view(), name='update_email'),
    url(r'^update_sex/$', UpdateUserSex.as_view(), name='update_sex'),
    url(r'^settings/$', UserApplicationListView.as_view(), name='settings'),
    url(r'^revoke_app/(?P<pk>\d+)/$', ApplicationRevokeView.as_view(), name='revoke_app'),
]

ldap-oauth2/sso/views.py
from django.core.mail.message import make_msgid
from django.views.generic import TemplateView

from account.models import UserProfile
from core.utils import DEGREES, HOSTELS, SEXES, SORTED_DISCIPLINES, TabNav


class IndexView(TemplateView):
    template_name = 'sso/index.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if request.user.is_authenticated:
            context['base_template'] = 'sso/logged_in.html'
        else:
            context['base_template'] = 'sso/root.html'

        return self.render_to_response(context)


tabs_list = [
    ('basic', 'Basic', 'basic.html'),
    ('api', 'APIs', 'api.html'),
    ('widgets', 'Widgets', 'widget.html'),
    ('best-practices', 'Best Practices', 'practices.html'),
    ('libraries', 'Libraries', 'library.html'),
    ('policy', 'Policy', 'policy.html'),
]


class DocView(TemplateView):
    template_name = 'sso/5-minutes-doc.html'
    tabs = [TabNav(tab[0], tab[1], tab[2], 'doc', tab[0] == 'basic') for tab in tabs_list]

    def get_context_data(self, **kwargs):
        context = super(DocView, self).get_context_data(**kwargs)
        context['login_js_url'] = 'https://gymkhana.iitb.ac.in/profiles/static/widget/js/login.min.js'
        context['Message_ID'] = make_msgid()
        context['SORTED_DISCIPLINES'] = SORTED_DISCIPLINES
        context['DEGREES'] = DEGREES
        context['HOSTELS'] = HOSTELS
        context['SEXES'] = SEXES
        context['USER_TYPES'] = UserProfile.objects.values_list('type').distinct()

        # Mark all tabs as inactive
        for tab_ in self.tabs:
            tab_.is_active = False

        tab = context.get('tab', '')
        for tab_ in self.tabs:
            if tab == tab_.tab_name:
                tab = tab_
                break
        else:
            tab = self.tabs[0]
        tab.is_active = True
        context['tabs'] = self.tabs
        context['active_tab'] = tab
        return context

ldap-oauth2/templates/sso/5-minutes-doc.html
{% extends 'sso/root.html' %}
{% load static %}
{% load absolute_url %}

{% block title %}
    Documentation - {{ active_tab.name }}
{% endblock %}

{% block cssLinks %}
    <link rel="stylesheet" type="text/css" href="{% static 'sso/css/doc.css' %}"/>
{% endblock %}

{% block body %}

    <h4>Writing a new application to is quite easy since the whole implementation is following the
        <a href="https://tools.ietf.org/html/rfc6749" target="_blank">RFC 6749</a> for OAuth 2.0</h4>
    <h4><a href="http://tutorials.jenkov.com/oauth2/index.html" target="_blank">Here</a> is a nice tutorial for OAuth
        2.0</h4>
    <h3 style="color: red">
        <b>IMPORTANT: READ BELOW BEFORE CONTINUING!!!</b> <br/> <br/>

        Profiles is intended to be used only by applications running on the server infrastructure
        of IIT Bombay Students' Gymkhana. If your application does not run on Gymkhana servers, DO NOT use Profiles, and
	check Computer Center's website for details on developing applications with IITB SSO integration. <br/><br/>

        If the above condition is not satisfied, your application may be deleted and your account blocked from
	Gymkhana services without prior notice. For any details, contact mlc@iitb.ac.in
    </h3>

    <ul id="tabs" class="nav nav-tabs" role="tablist" style="margin-top: 25px;">
        {% for tab in tabs %}
            <li role="presentation" {% if tab.is_active %}class="active"{% endif %}>
                <a href="#{{ tab.tab }}" id="{{ tab.tab }}-tab" role="tab" data-toggle="tab" data-url="{{ tab.url }}"
                   aria-controls="{{ tab.tab }}" data-title="Documentation - {{ tab.name }}">{{ tab.name }}</a>
            </li>
        {% endfor %}
    </ul>

    <div id="myTabContent" class="tab-content">

        {% for tab in tabs %}
            <div role="tabpanel" class="tab-pane fade in {% if tab.is_active %}active{% endif %}" id="{{ tab.tab }}"
                 aria-labelledby="{{ tab.tab }}-tab">
                {% with tab_template='sso/doc_includes/'|add:tab.template_name %}
                    {% include tab_template %}
                {% endwith %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block jsLinks %}
    <script src="{% static 'sso/js/anchor.min.js' %}" type="application/javascript"></script>
    <script type="application/javascript">
        anchors.add('h3');
    </script>
    <script src="{% static 'widget/js/login.js' %}" type="application/javascript"></script>
    <script type="application/javascript">
        window.history.pushState({}, '', '{{ active_tab.url }}');
        var is_widget_loaded = {% if active_tab.tab == 'widgets'  %}true{% else %}false{% endif %};
    </script>
    <script src="{% static 'sso/js/doc.js' %}" type="application/javascript"></script>
{% endblock %}

ldap-oauth2/templates/sso/index.html
{% extends base_template %}

{% block featurette %}
    <main class="masthead" role="main">
        <div class="container" style="color: #ffffff">
            <h1 style="font-size: 110px;">Profiles</h1>
            <p style="font-size: 30px; margin-bottom: 40px;">
                OAuth2 proxy built on IIT Bombay SSO for services on Students' Gymkhana
            </p>
            <div class="row" style="padding: 32px">
                <div class="col-md-6 form-group">
                    <a href="{% url 'doc' %}" class="btn btn-outline-inverse btn-lg">Docs for Developers</a>
                </div>
                <div class="col-md-6 form-group">
                    <a href="{% url 'user:home' %}" class="btn btn-outline-inverse btn-lg">User Profile Home</a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

ldap-oauth2/templates/sso/logged_in.html
{% extends 'sso/root.html' %}

{% block navbar_right_link %}
    <li>
        <div class="dropdown">
            <button class="btn dropdown-button dropdown-toggle" id="dLabel" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" style="padding: 10px;">
                <span class="glyphicon glyphicon-cog" style="font-size: 25px;"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dLabel">
                <li><a href="{% url 'user:settings' %}">Apps you're connected to</a></li>
                <li><a href="{% url 'oauth2_provider:list' %}">Apps you created</a></li>
            </ul>
        </div>
    </li>
    <li><a href="{% url 'user:home' %}"><strong>
        {% if user %}
            {{ user.first_name }}
        {% else %}
            Unknown User
        {% endif %}
    </strong></a></li>
    <li>
        <a href="{% url 'account:logout' %}
        {% if request.uri %}
        ?next={{ request.uri|urlencode }}
        {% endif %}">Logout</a>
    </li>
{% endblock %}

ldap-oauth2/templates/sso/root.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title> {% block title %} Profiles IITB {% endblock %} </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'sso/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'sso/css/root.css' %}"/>
    {% block cssLinks %}
    {% endblock %}
</head>

<body>

<div id="error-alert" class="alert alert-danger alert-dismissiable navbar-fixed-top container" role="alert"
     style="z-index: 2000; max-width: 750px; display:none;">
    <button id="error-alert-close" type="button" class="close" data-dismiss="alert" aria-label="Close"><span
            aria-hidden="true">×</span></button>
    <span class="sr-only">Error:</span>
    <div id="error-alert-content"></div>
</div>

<!-- Fixed navbar -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">Profiles</a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'doc' %}">Documentation</a></li>
                {% block navbar_left_link %}
                {% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% block navbar_right_link %}
                {% endblock %}
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

{% block featurette %}
{% endblock %}

<div class="container">
    {% block body %}
    {% endblock %}

    <div class="site-footer">
        <div class="row text-center">
            <div class="col-md-4 form-group">
                &copy; {% now "Y" %} {{ request.get_host }}
            </div>
            <div class="col-md-2 form-group">
                <a href="{% url 'doc' %}">Documentation</a>
            </div>
            <div class="col-md-2 form-group">
                <a href="https://github.com/iitb-gymkhana/ldap-oauth2/blob/master/contributors.md" target="_blank">Contributors</a>
            </div>
            <div class="col-md-2 form-group">
                <a href="https://github.com/iitb-gymkhana/ldap-oauth2/" target="_blank">Source Code</a>
            </div>
            <div class="col-md-2 form-group">
                <a href="https://github.com/iitb-gymkhana/ldap-oauth2/issues" target="_blank">Bugs || Suggestions</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'sso/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'sso/js/js.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'sso/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'sso/js/root.js' %}"></script>
{% block jsLinks %}
{% endblock %}
</body>
</html>