ldap-oauth2/sso/urls.py
import re

import oauth2_provider.urls
from django.conf import settings

from django.urls import re_path as url
from django.conf.urls import include

# from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.views.static import serve

import account.urls
import application.urls
import resources.urls
import user_resource.urls
import widget.urls
import internal.urls

from .views import DocView, IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('doc/', DocView.as_view(), name='doc'),
    url(r'^doc/(?P<tab>[\w-]+\w+)/$', DocView.as_view(), name='doc'),
    path('admin/', admin.site.urls),
    path('oauth/', include((application.urls, 'oauth'), namespace='oauth')),
    path('oauth/', include((oauth2_provider.urls, 'oauth2_provider'), namespace='oauth2_provider')),
    path('account/', include((account.urls, 'account'), namespace='account')),
    path('user/', include((user_resource.urls, 'user'), namespace='user')),
    path('resources/', include((resources.urls, 'resources'), namespace='resources')),
    path('internal/', include((internal.urls, 'internal'), namespace='internal')),
    path('widget/', include((widget.urls, 'widgets'), namespace='widgets')),
]

# Fail safe! If nginx is down, this might come handy.
#urlpatterns += [
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.STATIC_ROOT,
#        }
#        ),
#    url(r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')), serve,
#        kwargs={
#            'document_root': settings.MEDIA_ROOT,
#        }
#        ),
#]

ldap-oauth2/user_resource/urls.py
# from django.conf.urls import include, url
from django.conf.urls import include
from django.urls import re_path as url
from rest_framework.routers import DefaultRouter

from .views.api import UserViewset
from .views.home import (ApplicationRevokeView, UpdateInstiAddressView, UpdateMobileNumberView, UpdateProgramView,
                         UpdateSecondaryEmailView, UpdateUserProfilePicture, UpdateUserSex, UserApplicationListView,
                         UserHomePageView)

router = DefaultRouter()
router.register('user', UserViewset, basename='user')

urlpatterns = [
    url(r'^api/', include((router.urls, 'api'), namespace='api')),
    url(r'^$', UserHomePageView.as_view(), name='home'),
    url(r'^update_pp/$', UpdateUserProfilePicture.as_view(), name='update_pp'),
    url(r'^update_address/$', UpdateInstiAddressView.as_view(), name='update_address'),
    url(r'^update_program/$', UpdateProgramView.as_view(), name='update_program'),
    url(r'^update_mobile/$', UpdateMobileNumberView.as_view(), name='update_mobile'),
    url(r'^update_email/$', UpdateSecondaryEmailView.as_view(), name='update_email'),
    url(r'^update_sex/$', UpdateUserSex.as_view(), name='update_sex'),
    url(r'^settings/$', UserApplicationListView.as_view(), name='settings'),
    url(r'^revoke_app/(?P<pk>\d+)/$', ApplicationRevokeView.as_view(), name='revoke_app'),
]

ldap-oauth2/user_resource/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from six import python_2_unicode_compatible
# from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from application.models import Application
from core.utils import DEGREES, HOSTELS, HOSTELS_WITH_WINGS, ROOM_VALIDATION_REGEX, SORTED_DISCIPLINES


def validate_join_year(value):
    current_year = timezone.now().year
    if value < 1958:
        raise ValidationError(_('%d! Are you kidding me? IITB was not even there back then!' % value))
    if value > current_year:
        raise ValidationError(_('Welcome kiddo, welcome to IITB in future!'))


def validate_graduation_year(value):
    current_year = timezone.now().year
    if value < 1958:
        raise ValidationError(_('%d! Are you kidding me? IITB was not even there back then!' % value))
    if value > (current_year + 6):
        raise ValidationError(_('Please enter your expected graduation year'))


@python_2_unicode_compatible
class InstituteAddress(models.Model):
    user = models.OneToOneField(User, related_name='insti_address', on_delete=models.CASCADE)
    room = models.CharField(max_length=8, null=True, blank=True)
    hostel = models.CharField(max_length=8, choices=HOSTELS, null=True, blank=True)
    _history_ = HistoricalRecords()

    def clean(self):
        if self.room:
            if self.hostel in HOSTELS_WITH_WINGS:
                if not ROOM_VALIDATION_REGEX.match(self.room):
                    raise ValidationError(_('Room number must have wing name like A-123'))

    def __str__(self):
        if self.hostel:
            if self.room:
                return "%s-%s" % (self.hostel, self.room)
            return self.hostel
        return ''


@python_2_unicode_compatible
class Program(models.Model):
    user = models.OneToOneField(User, related_name='program', on_delete=models.CASCADE)
    department = models.CharField(max_length=16, choices=SORTED_DISCIPLINES, null=True, blank=True)
    join_year = models.PositiveSmallIntegerField(null=True, blank=True, validators=[validate_join_year])
    graduation_year = models.PositiveSmallIntegerField(null=True, blank=True, validators=[validate_graduation_year])
    degree = models.CharField(max_length=16, choices=DEGREES, null=True, blank=True)
    _history_ = HistoricalRecords()

    def __str__(self):
        return "%s, %s" % (self.get_degree_display(), self.get_department_display())


@python_2_unicode_compatible
class ContactNumber(models.Model):
    user = models.ForeignKey(User, related_name='contacts', on_delete=models.CASCADE)
    number = models.CharField(max_length=16)
    _history_ = HistoricalRecords()

    def __str__(self):
        return self.number


@python_2_unicode_compatible
class SecondaryEmail(models.Model):
    user = models.ForeignKey(User, related_name='secondary_emails', on_delete=models.CASCADE)
    email = models.EmailField()
    _history_ = HistoricalRecords()

    def __str__(self):
        return self.email


@python_2_unicode_compatible
class SentMessage(models.Model):
    message_id = models.CharField(max_length=256)
    sender = models.ForeignKey(Application, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    error_message = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message_id

ldap-oauth2/user_resource/forms.py
from django import forms
from django.template.defaultfilters import filesizeformat
# from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _

from core.utils import SEXES, get_choices_with_blank_dash

from .models import InstituteAddress, Program


class ProfilePictureForm(forms.Form):
    profile_picture = forms.ImageField()

    def clean_profile_picture(self):
        profile_picture = self.cleaned_data['profile_picture']
        content_type = profile_picture.content_type.split('/')[0]
        if content_type in ['image']:
            if profile_picture.size > 5242880:
                raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (
                    filesizeformat(5242880), filesizeformat(profile_picture.size)))
        else:
            raise forms.ValidationError(_('File type is not supported'))
        return profile_picture


class SexUpdateForm(forms.Form):
    sex = forms.ChoiceField(choices=get_choices_with_blank_dash(SEXES), required=False,
                            widget=forms.Select(
                                attrs={'class': 'form-control', },
                            ))


class InstituteAddressForm(forms.ModelForm):
    class Meta:
        model = InstituteAddress
        fields = ['hostel', 'room']
        widgets = {
            'hostel': forms.Select(
                attrs={'class': 'form-control', },
            ),
            'room': forms.TextInput(
                attrs={'class': 'form-control', },
            ),
        }


class ProgramForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(ProgramForm, self).clean()
        join_year = cleaned_data.get('join_year')
        graduation_year = cleaned_data.get('graduation_year')

        if join_year and graduation_year:
            if graduation_year <= join_year:
                validation_err = forms.ValidationError(_('How come you graduated before you joined?'), code='bad_input')
                self.add_error('graduation_year', validation_err)

            if join_year >= graduation_year:
                validation_err = forms.ValidationError(
                    _('How come you joined after you graduated? You must be in alternate timeline!'), code='bade_input')
                self.add_error('join_year', validation_err)

    class Meta:
        model = Program
        fields = ['department', 'join_year', 'graduation_year', 'degree']
        widgets = {
            'department': forms.Select(
                attrs={'class': 'form-control', },
            ),
            'join_year': forms.NumberInput(
                attrs={'class': 'form-control', },
            ),
            'graduation_year': forms.NumberInput(
                attrs={'class': 'form-control', },
            ),
            'degree': forms.Select(
                attrs={'class': 'form-control', },
            ),
        }
        labels = {
            'department': 'Discipline',
            'graduation_year': '(Expected) Graduation Year',
        }

ldap-oauth2/user_resource/views/api.py
import logging
from smtplib import SMTPException

from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from oauth2_provider.contrib.rest_framework.permissions import TokenHasScope
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.status import HTTP_400_BAD_REQUEST

from ..models import SentMessage
from ..oauth import DEFAULT_FIELDS, SCOPE_TO_FIELD_MAP, USER_FIELDS
from ..serializers import SendMailSerializer, UserSerializer

logger = logging.getLogger(__name__)


class UserViewset(viewsets.GenericViewSet):
    required_scopes = ['basic']
    permission_classes = [TokenHasScope]
    serializer_class = UserSerializer

    def get_queryset(self):
        token = self.request.auth
        user = token.user
        return User.objects.all().filter(pk=user.id)

    def list(self, request):
        user_queryset = self.get_queryset().first()
        fields = request.query_params.get('fields')
        granted_scopes = request.auth.scope
        granted_scopes = granted_scopes.split()
        granted_fields = []
        for scope in granted_scopes:
            granted_fields.extend(SCOPE_TO_FIELD_MAP[scope])

        if fields is None:
            fields = []
        else:
            fields = fields.split(',')
            fields = [field.strip() for field in fields if field.strip()]
        fields = set(fields)
        all_fields = set(DEFAULT_FIELDS + USER_FIELDS)
        undefined_fields = list(fields - all_fields)
        if undefined_fields:
            error_message = {
                'detail': 'fields (%s) not found' % ', '.join(undefined_fields)
            }
            return Response(error_message, status=HTTP_400_BAD_REQUEST)

        allowed_fields = list(set(fields).intersection(set(granted_fields)))
        user_serialized = UserSerializer(user_queryset, context={'fields': allowed_fields}).data
        return Response(user_serialized)

    @action(methods=['POST'], required_scopes=['send_mail'], detail=False)
    def send_mail(self, request):
        token = request.auth
        app = token.application
        app_admin = token.application.user
        user = self.get_queryset().first()
        mail = SendMailSerializer(data=request.data)
        if mail.is_valid():
            subject = '[SSO] [%s] %s' % (app.name, mail.validated_data.get('subject'))
            body = ('%s\n\n\n'
                    'Sent via SSO by %s\n\n'
                    'You received this message because you\'ve provided the email sending'
                    ' permission to the application')
            body = body % (mail.validated_data.get('message'), app.name)
            from_email = '%s <%s>' % (app_admin.first_name, app_admin.email)
            email_message = EmailMessage(
                subject=subject,
                body=body,
                from_email=from_email,
                to=[user.email],
                reply_to=mail.validated_data.get('reply_to'),
            )
            message = email_message.message()
            sent_message = SentMessage(
                message_id=message['Message-ID'],
                sender=app,
                user=user,
            )
            response_data = {
                'Message-ID': message['Message-ID'],
                'status': True,
            }
            try:
                email_message.send()
                sent_message.status = True
                response_data['status'] = True
            except SMTPException as err:
                sent_message.status = False,
                sent_message.error_message = err.message
                logger.error(err)
                response_data['status'] = False
            sent_message.save()
            return Response(response_data)
        else:
            return Response(mail.errors, status=HTTP_400_BAD_REQUEST)

ldap-oauth2/templates/user_resources/application_list.html
{% extends 'sso/logged_in.html' %}
{% load static %}

{% block title %}
    Connected Applications
{% endblock %}

{% block body %}
    {% static 'sso/img/default_logo.jpg' as default_image %}
    <div class="row">
        <div class="col-md-6">
            <h1>Apps connected to your account</h1>

            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                {# applications is a dictionary of application to scopes #}
                {% for application, scopes in applications.items %}
                    <div class="panel panel-default">
                        <div role="button" data-toggle="collapse" data-parent="#accordion"
                             data-target="#application{{ application.id }}"
                             class="panel-heading">
                            <div class="media">
                                <div class="media-left media-middle">
                                    <img class="media-object"
                                         src="{{ application.get_logo_url|default_if_none:default_image }}"
                                         width="50" height="50" alt="Application Logo">
                                </div>
                                <div class="media-body media-middle">
                                    <h3 class="media-heading">{{ application.name }}</h3>
                                </div>
                                {% if not application.is_anonymous %}
                                    <div class="media-right media-middle">
                                        <a href="{% url 'user:revoke_app' application.id %}"
                                           class="btn btn-danger revoke-button">Revoke</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div id="application{{ application.id }}" class="panel-collapse collapse" role="tabpanel"
                             aria-labelledby="headingOne">
                            <div class="panel-body">
                                {{ application.description }} <br><br>
                                <b>
                                    This application has following permission:
                                    <ul>
                                        {% for scope in scopes %}
                                            <li>
                                                {{ scope }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </b>

                                <div>Developed By:
                                    <a href="mailto:{{ application.user.email }}">{{ application.user.username }}</a>
                                </div>
                                {% if application.website %}
                                    <div>
                                        <a href="{{ application.website }}" target="_blank">Visit Website</a>
                                    </div>
                                {% endif %}
                                {% if application.privacy_policy %}
                                    <div>
                                        <a href="{{ application.privacy_policy }}" target="_blank">Read privacy policy</a>
                                    </div>
                                {% endif %}
                            </div>

                        </div>
                    </div>

                {% empty %}
                    No apps found
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

ldap-oauth2/templates/user_resources/form_error.html
{% extends 'sso/logged_in.html' %}
{% load static %}

{% block cssLinks %}
    <link rel="stylesheet" type="text/css" href="{% static 'user_resource/css/home.css' %}"/>
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-6" style="float: none; margin: auto;">
            <form role="form" action="" method="post" class="user-profile-form">
                <fieldset class="fieldset-border">
                    <legend class="marginless">{{ form_title }}</legend>
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <ul>
                            {% for error in form.non_field_errors %}
                                <li><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {% for field in form %}
                        <div class="form-group {% if field.errors %} has-error {% endif %}">
                            {{ field.label_tag }}
                            {% if field.errors %}
                                <ul>
                                    {% for error in field.errors %}
                                        <li><span class="help-block">{{ error }}</span></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <input class="btn btn-primary" type="submit" value="Save"/>
                </fieldset>
            </form>
        </div>
    </div>

{% endblock %}

ldap-oauth2/templates/user_resources/home.html
{% extends 'sso/logged_in.html' %}
{% load static %}
{% load model_media %}

{% block title %}
    Home
{% endblock %}

{% block cssLinks %}
    <!--suppress HtmlFormInputWithoutLabel -->
    <link rel="stylesheet" type="text/css" href="{% static 'user_resource/css/home.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'user_resource/css/timer.css' %}"/>
    <style>
        .user-profile-form {
            margin-top: 40px;
        }
    </style>
{% endblock %}

{% block jsLinks %}
    <script type="application/javascript">
        var profileBadgeFormSubmitUrl = "{% url 'user:update_pp' %}";
    </script>
    <script type="application/javascript" src="{% static 'user_resource/js/home.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6" style="float: none; margin: auto;">
            <form role="form" method="post" enctype="multipart/form-data" id="profile-badge-form">
                <fieldset class="fieldset-border">

                    <legend class="marginless">Profile Badge</legend>
                    {% csrf_token %}
                    <div class="media">
                        <div class="media-left">
                            {% static 'sso/img/nophoto.png' as default_user_profile_picture %}

                            <div class="image-glyphicon-wrapper">
                                <img id="profile-picture"
                                     class="media-object"
                                     src="{{ user_profile_picture|default_if_none:default_user_profile_picture }}"
                                     alt="{{ user.username }}"
                                     width="128" height="128"
                                     style="border: rgba(0, 0, 0, 0.13) 1px solid;"
                                        />
                                <input id="pp-upload-input" class="pp-upload-input" type="file" name="profile_picture"
                                       accept="image/jpeg, image/png"/>

                                <div role="button" class="pp-upload-button">
                                    <span class="glyphicon glyphicon-camera"></span>
                                </div>
                            </div>

                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">{{ user.first_name|add:" "|add:user.last_name }}</h4>

                            <div><span class="glyphicon glyphicon-envelope"></span>
                                <a href="mailto:{{ user.email }}">{{ user.email }}</a></div>
                            {% if ldap_number and ldap_number != '' %}
                                <div><span class="glyphicon glyphicon-phone"></span>{{ ldap_number }} </div>
                            {% endif %}
                            {% if insti_address_form.hostel.value %}
                                <div><span class="glyphicon glyphicon-home"></span>
                                    {{ user.insti_address.get_hostel_display }}
                                    {% if insti_address_form.room.value %}
                                        | Room {{ insti_address_form.room.value }}
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </fieldset>
            </form>
            <form role="form" action="{% url 'user:update_sex' %}" method="post" class="user-profile-form">
                <fieldset class="fieldset-border">
                    <legend class="marginless">Sex</legend>
                    {% csrf_token %}
                    {% if sex_update_form.non_field_errors %}
                        <ul>
                            {% for error in sex_update_form.non_field_errors %}
                                <li><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class="form-group {% if sex_update_form.sex.errors %} has-error {% endif %}">
                        {{ sex_update_form.sex.label_tag }}
                        {% if sex_update_form.sex.errors %}
                            <ul>
                                {% for error in sex_update_form.sex.errors %}
                                    <li><span class="help-block">{{ error }}</span></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        {{ sex_update_form.sex }}
                    </div>
                    <input class="btn btn-primary" type="submit" value="Save"/>
                </fieldset>
            </form>
            <form role="form" action="{% url 'user:update_mobile' %}" method="post" class="user-profile-form">
                <fieldset class="fieldset-border">
                    <legend class="marginless">Contact Numbers</legend>
                    {% csrf_token %}
                    {% if ldap_number and ldap_number != '' %}
                        <div class="form-group">
                            <input class="form-control" type="text" value="{{ ldap_number }}" disabled/>
                        </div>
                    {% endif %}
                    {% for mobile_number in mobile_numbers %}
                        <div class="form-group">
                            <div class="input-group">
                                <input class="form-control" type="text" name="phone"
                                       value="{{ mobile_number.number }}"/>
                                <a class="remove-input input-group-addon backgroundless-input-group-addon" href="#">
                                    <span class="glyphicon glyphicon-minus"></span>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="input-group">
                            <input class="form-control" type="text" name="phone">
                            <a class="add-input input-group-addon backgroundless-input-group-addon" href="#">
                                <span class="glyphicon glyphicon-plus"></span>
                            </a>
                        </div>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Save"/>
                </fieldset>
            </form>
            <form role="form" action="{% url 'user:update_email' %}" method="post" class="user-profile-form">
                <fieldset class="fieldset-border">
                    <legend class="marginless">Emails</legend>
                    {% csrf_token %}
                    {% if gpo_email %}
                        <div class="form-group">
                            <input class="form-control" type="email" value="{{ gpo_email }}" disabled/>
                        </div>
                    {% endif %}
                    {% for email in secondary_emails %}
                        <div class="form-group">
                            <div class="input-group">
                                <input class="form-control" type="text" name="email" value="{{ email.email }}"/>
                                <a class="remove-input input-group-addon backgroundless-input-group-addon" href="#">
                                    <span class="glyphicon glyphicon-minus"></span>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="input-group">
                            <input class="form-control" type="email" name="email">
                            <a class="add-input input-group-addon backgroundless-input-group-addon" href="#">
                                <span class="glyphicon glyphicon-plus"></span>
                            </a>
                        </div>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Save"/>
                </fieldset>
            </form>
            <form role="form" action="{% url 'user:update_address' %}" method="post" class="user-profile-form">
                <fieldset class="fieldset-border">
                    <legend class="marginless">Institute Address</legend>
                    {% csrf_token %}
                    {% if insti_address_form.non_field_errors %}
                        <ul>
                            {% for error in insti_address_form.non_field_errors %}
                                <li><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class="form-group {% if insti_address_form.hostel.errors %} has-error {% endif %}">
                        {{ insti_address_form.hostel.label_tag }}
                        {% if insti_address_form.hostel.errors %}
                            <ul>
                                {% for error in insti_address_form.hostel.errors %}
                                    <li><span class="help-block">{{ error }}</span></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        {{ insti_address_form.hostel }}
                    </div>
                    <div class="form-group {% if insti_address_form.room.errors %} has-error {% endif %}">
                        {{ insti_address_form.room.label_tag }}
                        {% if insti_address_form.room.errors %}
                            <ul>
                                {% for error in insti_address_form.room.errors %}
                                    <li><span class="help-block">{{ error }}</span></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        {{ insti_address_form.room }}
                    </div>
                    <input class="btn btn-primary" type="submit" value="Save"/>
                </fieldset>
            </form>
            <form role="form" action="{% url 'user:update_program' %}" method="post" class="user-profile-form">
                <fieldset class="fieldset-border">
                    <legend class="marginless">Program</legend>
                    {% csrf_token %}
                    {% if program_form.non_field_errors %}
                        <ul>
                            {% for error in program_form.non_field_errors %}
                                <li><strong>{{ error }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% if roll_number %}
                        <div class="form-group">
                            <label for="roll_number">Roll Number:</label>
                            <input class="form-control" id="roll_number" type="text" value="{{ roll_number }}"
                                   disabled/>
                        </div>
                    {% endif %}
                    {% for field in program_form %}
                        <div class="form-group {% if field.errros %} has-error {% endif %}">
                            {{ field.label_tag }}
                            {% if field.errors %}
                                <ul>
                                    {% for error in field.errors %}
                                        <li><span class="help-block">{{ error }}</span></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <input class="btn btn-primary" type="submit" value="Save"/>
                </fieldset>
            </form>


        </div>
    </div>
{% endblock %}